### ISSUE TITLE
voice sdk / wit.ai transcription not working on quest 3

### ISSUE THREAD

**Issue by swang81** [wit-ai/voicesdk-unreal#51]
I copy the issus from meta communityforums. I also have the same question. 
The original post is here.
[https://communityforums.atmeta.com/t5/Unreal-VR-Development/voice-sdk-wit-ai-transcription-not-working-on-quest-3/m-p/1203015](url)

This is my setup:

Unreal Engine 5.4.2
Meta Quest 3 (up to date)
Voice SDK / Wit.ai app (latest)
I followed the guide for transcripton here: https://developer.oculus.com/documentation/unreal/vsdk-transcription

Everything works if I test on Windows. But wenn I package the app for the quest and activate voice/transcription the app closes immedatly if I start speaking. There are no errors. the last lines in the log file are:

```
[2024.06.08-16.03.50:036][795]LogWit: Display: ActivateVoiceInput: activated voice input
[2024.06.08-16.03.51:048][867]LogWit: Display: BeginStreamRequest: starting stream request

```
What am I doing wrong?

**Comment by IanSlatteryMeta** [comment]
Thanks for bringing this issue to our attention. We have been able to recreate the failure and have identified a potential solution that will be a part of our next release. Prior to that release, a manual fix can be achieved by replacing line 37 in `Plugins\wit-unreal\Source\Wit\Private\WitModule.cpp` with `HttpManager->UpdateConfigs();`

**Comment by weather-sketch** [comment]
Hi, I encountered the exact same issues on my project. But I am using Unity, so I can't use the solution here. I can't find the .cpp file in my folder. Is there any way to fix the issues on Unity. Thanks a lot!

**Comment by IanSlatteryMeta** [comment]
Any issues with VoiceSDK using Unity should be reported at wit-unity](https://github.com/wit-ai/wit-unity). They are likely unrelated as the codebases are distinct. This particular issue is directly related to builds using Unreal 5.4

**Comment by alefriant** [comment]
Hi @IanSlatteryMeta 
Has this been solved in the release 67? I wasn't able to find any changelog after the v63. 
If not, when could we expect a v68 with the fix included for the Quest platforms?

**Comment by alefriant** [comment]
@swang81 
Hi!, Do you know if this was solved in v67?

**Comment by swang81** [comment]
I use the voiceSDK from epic marketplace. it still doesn't work based on 67

**Comment by biomedtechnologylab** [comment]
Hi, I'm also still running into this problem using the marketplace version (that is inaccessible atm due it not being ported to FAB).
I tried to adjust the line for the manual fix, but when I try to rebuild the plugin, it throws errors on the DictationService.h file:

Source\Wit\Public\Dictation\Service\DictationService.h(31): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
Source\Wit\Public\Dictation\Service\DictationService.h(31): error C2143: syntax error: missing ',' before '*'
Source\Wit\Public\Dictation\Service\DictationService.h(51): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
Source\Wit\Public\Dictation\Service\DictationService.h(51): error C2143: syntax error: missing ';' before '*'
Source\Wit\Public\Dictation\Service\DictationService.h(51): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
Source\Wit\Public\Dictation\Service\DictationService.h(26): error C2789: 'UDictationService::FDictationConfiguration': an object of const-qualified type must be initialized
Source\Wit\Public\Dictation\Service\DictationService.h(51): note: see declaration of 'UDictationService::FDictationConfiguration'
Source\Wit\Public\Dictation\Service\DictationService.h(31): error C4458: declaration of 'FDictationConfiguration' hides class member
Source\Wit\Public\Dictation\Service\DictationService.h(51): note: see declaration of 'UDictationService::FDictationConfiguration'
Source\Wit\Public\Dictation\Service\DictationService.h(31): error C2065: 'Configuration': undeclared identifier
Source\Wit\Public\Dictation\Service\DictationService.h(31): error C2065: 'ConfigurationToUse': undeclared identifier
Intermediate\Build\Win64\UnrealEditor\Inc\Wit\UHT\DictationService.gen.cpp(99): error C2789: 'UDictationService::FDictationConfiguration': an object of const-qualified type must be initialized
Source\Wit\Public\Dictation\Service\DictationService.h(51): note: see declaration of 'UDictationService::FDictationConfiguration'

When I had tried to install the plugin via the one-click installer, I got the same errors.
